@baseUrlDev = https://ynjaek8j7a.execute-api.us-east-1.amazonaws.com/dev
@baseUrlProd = https://t6yu3oclhk.execute-api.us-east-1.amazonaws.com/prod

### Get SNS Topics List

GET {{baseUrlProd}}/sns

### Subscribe to an SNS Topic

POST {{baseUrlProd}}/sns
Content-Type: application/json

{
    "email": "example@email.com",
    "topicArn": "arn:aws:sns:us-east-1:831076986893:test2"
}
